Create pulseSensor.ino
victoriadealba/IOTMonitoring pull request #3
Opened 2023-11-05 21:08 UTC by kelseyblanchard

Juliana's PulseSensor code sending to realtime database on Firebase and Kelsey's additions to read in the realtime data from Firebase and sound of the active buzzer

2023-11-05 21:13 UTC, victoriadealba requested changes
change the file name

2023-11-05 21:20 UTC, FernFeather reviewed
good

2023-11-05 21:21 UTC, FernFeather approved these changes

2023-11-05 21:21 UTC, FernFeather approved these changes

2023-11-05 21:22 UTC, FernFeather approved these changes

2023-11-07 18:07 UTC, victoriadealba approved these changes

2023-11-07 18:07 UTC, merged